# Generated by Django 6.0 on 2026-01-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='code',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emp_id',
        ),
    ]
