# Generated by Django 6.0 on 2026-03-01 00:33

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[400, 400], upload_to='profile/'),
        ),
    ]
