# Generated by Django 6.0 on 2026-03-02 00:44

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[400, 400], storage='users.supabase_storage.SupabaseStorage', upload_to='profile/'),
        ),
    ] already on the Supabase database. Noth
