# Generated by Django 6.0 on 2026-02-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_manufacturer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaler',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='wholesaler',
            constraint=models.UniqueConstraint(condition=models.Q(('contact__isnull', False)), fields=('contact',), name='unique_contact_if_present'),
        ),
    ]
