# Generated by Django 6.0 on 2026-02-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_wholesaler_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaler',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='wholesaler',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email_if_present'),
        ),
    ]
