# Generated by Django 6.0 on 2026-02-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_wholesaler_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wholesaler',
            name='unique_contact_if_present',
        ),
        migrations.RemoveConstraint(
            model_name='wholesaler',
            name='unique_email_if_present',
        ),
        migrations.AddConstraint(
            model_name='wholesaler',
            constraint=models.UniqueConstraint(condition=models.Q(('contact__isnull', False), models.Q(('contact', ''), _negated=True)), fields=('contact',), name='unique_contact_if_present'),
        ),
        migrations.AddConstraint(
            model_name='wholesaler',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='unique_email_if_present'),
        ),
    ]
