# Generated by Django 6.0 on 2026-02-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_wholesaler_unique_contact_if_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
