# Generated by Django 6.0 on 2026-03-07 07:31

import quickmeds_backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_medicine_dosage_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=quickmeds_backend.storage_backends.SupabaseImageStorage(), upload_to='medicine_images/'),
        ),
    ]
