# Generated by Django 6.0 on 2026-04-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'invalid': 'Enter a valid strength value (e.g. 500.00).', 'max_digits': 'Strength limit is 9999.99'}, max_digits=6, null=True),
        ),
    ]
