# Generated by Django 6.0 on 2026-04-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_medicine_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'max_decimal_places': 'Strength can only have 2 decimal places', 'max_digits': 'Strength must be 9999.99 or less', 'max_whole_digits': 'Strength must be 9999.99 or less'}, max_digits=6, null=True),
        ),
    ]
