# Generated by Django 6.0 on 2026-04-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_medicine_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
