# Generated by Django 6.0 on 2026-01-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='receipt_number',
        ),
    ]
