# Generated by Django 6.0 on 2026-01-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_options_sale_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='unit_price',
        ),
    ]
