# Generated by Django 6.0 on 2026-03-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_saleitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
