# Generated by Django 6.0 on 2026-03-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saleitem_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Archived', 'Archived')], db_index=True, default='Completed', max_length=50),
        ),
    ]
